spring.application.name=TipsManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/tip_management
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:h2:file:C:/h2db/Tips;AUTO_SERVER=TRUE
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=123
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console


logging.level.org.springframework.security=DEBUG


pandascore.api.url=https://api.pandascore.co
pandascore.api.key=jd4P_uiouLdTv2uNPBNy3zkYo1YSiH7obCy5ZO9GjuFaVla5VdA